#ifndef LIBTUX4KIDSADMIN_GLOBAL_H
#define LIBTUX4KIDSADMIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBTUX4KIDSADMIN_LIBRARY)
#  define LIBTUX4KIDSADMINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBTUX4KIDSADMINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBTUX4KIDSADMIN_GLOBAL_H
